// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BotTelegramNET.Models
{
    public partial class tb_configuracao_financeira
    {
        [Key]
        public int id_configuracao_financeira { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? cf_juros_dia { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? cf_parcela_juros { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? cf_desconto_pagamento { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? cf_desconto_grupo_produto { get; set; }
        public int? fk_grupo { get; set; }

        [ForeignKey("fk_grupo")]
        [InverseProperty("tb_configuracao_financeira")]
        public virtual tb_grupo fk_grupoNavigation { get; set; }
    }
}